"""Repository Protocols — services depend on these, not on CSV details.

Lets us swap CSV -> SQLite (or any other backend) by adding one new class
that satisfies the Protocol; no service code changes.
"""
from __future__ import annotations

from typing import Iterable, List, Optional, Protocol

from .models import Budget, Category, Entry


class CategoryRepository(Protocol):
    def list(self) -> List[Category]: ...
    def get(self, category_id: str) -> Optional[Category]: ...
    def find_by_name(self, name: str) -> Optional[Category]: ...
    def add(self, category: Category) -> Category: ...
    def update(self, category: Category) -> Category: ...
    def delete(self, category_id: str) -> None: ...
    def replace_all(self, items: Iterable[Category]) -> None: ...


class EntryRepository(Protocol):
    def list(self) -> List[Entry]: ...
    def get(self, entry_id: str) -> Optional[Entry]: ...
    def add(self, entry: Entry) -> Entry: ...
    def update(self, entry: Entry) -> Entry: ...
    def delete(self, entry_id: str) -> None: ...
    def replace_all(self, items: Iterable[Entry]) -> None: ...


class BudgetRepository(Protocol):
    def list(self) -> List[Budget]: ...
    def get(self, budget_id: str) -> Optional[Budget]: ...
    def find_by_category(self, category: str) -> Optional[Budget]: ...
    def add(self, budget: Budget) -> Budget: ...
    def update(self, budget: Budget) -> Budget: ...
    def delete(self, budget_id: str) -> None: ...
    def replace_all(self, items: Iterable[Budget]) -> None: ...
